python sample.py \
    --ckpt_dir="outputs/v2/global_step_80000/" \
    --style_image_path="/data/ocr/namvt17/FontDiffuser/iam_data/train/TargetImage/094/094+leading.png" \
    --save_image \
    --character_input \
    --content_character="defence" \
    --save_image_dir="outputs/v2/80k" \
    --device="cuda:0" \
    --algorithm_type="dpmsolver++" \
    --guidance_type="classifier-free" \
    --guidance_scale=7.5 \
    --num_inference_steps=20 \
    --method="multistep"
