python sample.py \
    --ckpt_dir="outputs/v2/global_step_40000/" \
    --content_image_path="/data/ocr/namvt17/FontDiffuser/iam_data/train/ContentImage/arial/grey.jpg" \
    --style_image_path="/data/ocr/namvt17/FontDiffuser/iam_data/train/TargetImage/023/023+meeting.png" \
    --save_image \
    --save_image_dir="outputs/v2/40k" \
    --device="cuda:0" \
    --algorithm_type="dpmsolver++" \
    --guidance_type="classifier-free" \
    --guidance_scale=7.5 \
    --num_inference_steps=20 \
    --method="multistep"
